-- MySQL Script generated by MySQL Workbench
-- Sat Oct 14 13:17:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema otg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema otg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `otg` DEFAULT CHARACTER SET utf8 ;
USE `otg` ;

-- -----------------------------------------------------
-- Table `otg`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otg`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otg`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otg`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(100) NULL,
  `stutas` INT(11) NULL,
  `group_id` INT NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `balance` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `userscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_group_idx` (`group_id` ASC),
  CONSTRAINT `user_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `otg`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otg`.`qrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otg`.`qrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `qr` BLOB NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `user_qr_idx` (`user_id` ASC),
  CONSTRAINT `user_qr`
    FOREIGN KEY (`user_id`)
    REFERENCES `otg`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otg`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otg`.`cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(45) NOT NULL,
  `serial` VARCHAR(100) NOT NULL,
  `fire` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`, `hash`, `serial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otg`.`used_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otg`.`used_cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user_id` ASC),
  INDEX `card_idx` (`card_id` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`user_id`)
    REFERENCES `otg`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `card`
    FOREIGN KEY (`card_id`)
    REFERENCES `otg`.`cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
